visibility: ALL
aliases: []
output:
  intro: 'Players on %s:'
  label: 'ยง6%s: '
  list:
    colors: [WHITE, GRAY]
    delimiter: ' '
  count: 'ยง7Total:ยงf %d players'
groups:
  - name: Default
    permission: nerdlist.group.default
    priority: 0
debug: false
