visibility: ALL
output:
  intro: 'Players on %s:'
  label: '&6%s: '
  list:
    colors: [WHITE, GRAY]
    delimiter: ' '
  count: '&6Total:&f %d players'
groups:
  - name: Default
    permission: nerdlist.group.default
    priority: 0
